apiVersion: v1
kind: PersistentVolume
metadata:
  name: <APPLICATION>-pv-volume
  namespace: <NAMESPACE>
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
#    storage: 10Gi
    storage: <DESIRED_STORAGE_IN_GIGS>    
  accessModes:
    - ReadWriteOnce
  hostPath:
#COMMONLY USED PATHS:          
#    path: "/mnt/data/<DIRECTORY>"
#    path: "/mnt/vda1/<DIRECTORY>"
    path: "/path/to/directory"
